name: ğŸš€ Auto Archive Project Done Columns
on:
  schedule:
    - cron: '0 0 * * SUN'  # æ¯å‘¨æ—¥è‡ªåŠ¨è¿è¡Œ
    

jobs:
  add-archive-project-done-columns:
    runs-on: ubuntu-latest
    steps:
      - name: archive resolved issues
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ğŸ‘¨â€ğŸ’»ğŸ‘©â€ğŸ’»  Issues & PRs è¿›åº¦è·Ÿè¸ª
          column: Resolved Issues
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive

      - name: archive resolved prs
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ğŸ‘¨â€ğŸ’»ğŸ‘©â€ğŸ’»  Issues & PRs è¿›åº¦è·Ÿè¸ª
          column: Resolved PRs
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive
 

      - name: archive rejected prs
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: ğŸ‘¨â€ğŸ’»ğŸ‘©â€ğŸ’»  Issues & PRs è¿›åº¦è·Ÿè¸ª
          column: Rejected PRs
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          action: archive
 
