name: ğŸ‰ Auto Release Notify

# è‡ªåŠ¨å‘å¸ƒ action æ‰§è¡Œå®Œæˆåå†æ‰§è¡Œ (æ— è®ºæˆåŠŸå¤±è´¥éƒ½ä¼šæ‰§è¡Œ)
on:
  workflow_run:
    workflows: ["ğŸš€ Auto Release"]
    types:
      - completed

jobs:
  sync-site-lock:
    runs-on: ubuntu-latest
    # è‡ªåŠ¨å‘å¸ƒæˆåŠŸå
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      # å†…éƒ¨å¼€å‘å’ŒæœåŠ¡ç¾¤, å®˜æ–¹å¯¹å¤–è®¨è®ºç¾¤
      - name: Release success ding talk official group notify
        if: ${{ contains(github.ref_name, 'latest') }}
        uses: visiky/dingtalk-release-notify@main
        with:
          DING_TALK_TOKEN: |
            ${{ secrets.DING_TALK_ACCESS_TOKEN }}
            ${{ secrets.DING_TALK_GROUP_TOKEN }}
            ${{ secrets.DING_TALK_PUBLIC_TOKEN }}
          notify_title: 'ğŸ‰ {release_tag} å‘å¸ƒ ğŸ‰'
          notify_body: '### { title } <hr /> ![preview](https://gw.alipayobjects.com/zos/antfincdn/ISzgBCtgR/2c5c4aaa-4f40-46f7-8f6b-427fa9ff07bb.png) <hr /> { body } <hr />'
          at_all: false
          # enable_prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          enable_prerelease: false
