name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    if: github.actor != github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Need reproduce
        if: github.event.label.name == 'ğŸ¤” need reproduce'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æä¾›ä¸€ä¸ªå¯ä»¥åœ¨çº¿è®¿é—®çš„é“¾æ¥, æˆ–è€…ä½¿ç”¨ [codesandbox](https://codesandbox.io/s/29zle) æä¾›ç¤ºä¾‹å¹¶è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤ ([æŸ¥çœ‹æ›´å¤šæ¨¡æ¿](https://www.yuque.com/antv/vo4vyz/bam4vz)), 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, please provide an accessible link or usage [codesandbox](https://codesandbox.io/s/29zle) to describe the reproduction steps ([more template](https://www.yuque.com/antv/vo4vyz/bam4vz)). The issue will be closed without any replay within 15 days.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æä¾› gif, æˆªå›¾, ä»£ç ç‰‡æ®µ, é…ç½®ä¿¡æ¯, ç‰ˆæœ¬å·, å¯å¤ç°é“¾æ¥ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢! 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please complete the issue description, provide gifs, screenshots, config, version. And explain the reproduction steps in detail. Thanks so much for your cooperation! The issue will be closed without any replay within 15 days.

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€š, å¼ºçƒˆæ¨èä½ é˜…è¯» [æ Issue å‰å¿…è¯»](https://github.com/antvis/S2/issues/1904) å’Œ [å¦‚ä½•å‘å¼€æºé¡¹ç›®æäº¤æ— æ³•è§£ç­”çš„é—®é¢˜](https://zhuanlan.zhihu.com/p/25795393)ã€‚

            Hello @${{ github.event.issue.user.login }}, please fill in the relevant information according to the issue template to facilitate communication efficiently. recommend you to read [æ Issue å‰å¿…è¯»](https://github.com/antvis/S2/issues/1904) and [å¦‚ä½•å‘å¼€æºé¡¹ç›®æäº¤æ— æ³•è§£ç­”çš„é—®é¢˜](https://zhuanlan.zhihu.com/p/25795393), Thanks so much!

      - name: Enhancement
        if: github.event.label.name == 'âš¡ enhancement'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„å»ºè®®, æˆ‘ä»¬ä¼šåŠæ—¶è¯„ä¼°å’Œæ’æœŸ, è°¢è°¢!
            å½“ç„¶, å¦‚æœèƒ½è´¡çŒ® PR å¸®åŠ©æˆ‘ä»¬æ”¹è¿›, ä¸èƒœæ„Ÿæ¿€ï¼

            Hello, @${{ github.event.issue.user.login }}, thanks for your advice. We will evaluate and schedule in time. Thank you!
            you could implement it by yourself through the customization capabilities provided by S2. Thanks so much for your understanding.

      - name: Bug
        if: github.event.label.name == 'ğŸ› bug'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå¾ˆæŠ±æ­‰ç»™ä½ å¸¦æ¥äº†ä¸å¥½çš„ä½“éªŒ, æˆ‘ä»¬ä¼šå°½å¿«æ’æŸ¥é—®é¢˜å¹¶ä¿®å¤, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, We are so sorry for the bad experience. We will troubleshoot and fix the problem as soon as possible. Please pay attention to the follow-up change logs.

      - name: Usage
        if: github.event.label.name == 'ğŸ™€ usage' || github.event.label.name == 'â”question'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}, Issue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚ä½ å¯ä»¥è¯•ç€åœ¨ [antv s2 discussions](https://github.com/antvis/S2/discussions) æ–°å¼€ä¸€ä¸ª discussion, é€‰æ‹© `ğŸ™Q&A` ç±»åˆ«è¿›è¡Œæé—®, æˆ‘ä»¬ä¼šåŠæ—¶è¿›è¡Œè§£ç­”, æ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}. The Issue section is used for bug feedback and requirement discussion. You could open a new discussion in [antv s2 discussions](https://github.com/antvis/S2/discussions), choose the `ğŸ™Q&A` category to ask questions. We will answer in time. Thanks so much for your understanding.

      - name: Accepted
        if: github.event.label.name == 'âœ… accepted'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç»è¿‡æˆ‘ä»¬çš„åå¤è®¨è®º, ä½ çš„éœ€æ±‚ç°å·²è¢«é‡‡çº³, æˆ‘ä»¬ä¼šæ’æœŸå¼€å‘, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—ã€‚

            Hello, @${{ github.event.issue.user.login }}, your feature request has been accepted after our repeated discussion. We will schedule the development, please pay attention to the follow-up release logs.

      - name: Welcom PR
        if: github.event.label.name == 'â­ï¸ Welcom PR'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ çš„åé¦ˆæˆ‘ä»¬å·²æ”¶åˆ°, è¿™æ˜¯ä¸€ä¸ªå¼€æºé¡¹ç›®, æˆ‘ä»¬ä¹Ÿæ˜¯ç”¨è‡ªå·±çš„ä¸šä½™æ—¶é—´åœ¨ç»´æŠ¤, ä¸ºçˆ±å‘ç”µ, ç²¾åŠ›å®åœ¨æœ‰é™, ğŸ‘ğŸ» æ¬¢è¿æ ¹æ® [è´¡çŒ®æŒ‡å—](https://s2.antv.antgroup.com/manual/contribution) æäº¤ PR. ä¸€èµ·å‚ä¸åˆ°å¼€æºé¡¹ç›®çš„å»ºè®¾ä¸­.

            å¦‚æœä½ é‡åˆ°äº†é—®é¢˜ï¼Œæˆ–è€…å¯¹ [Issues](https://github.com/antvis/S2/issues) å’Œ [Discussions](https://github.com/antvis/S2/discussions) åˆ—è¡¨çš„é—®é¢˜æ„Ÿå…´è¶£ï¼Œå¯ä»¥**ç›´æ¥è®¤é¢†å¹¶å°è¯•ä¿®å¤**ï¼Œå¸®åŠ© S2 å˜å¾—æ›´å¥½ï¼ŒæœŸå¾…åœ¨ [è´¡çŒ®è€…åˆ—è¡¨](https://github.com/antvis/S2/graphs/contributors) é‡Œçœ‹è§ä½ çš„å¤´åƒã€‚

            Hello, @${{ github.event.issue.user.login }}, We have received your feedback, this is an open source project, we also use our spare time to maintain, for love power generation, energy is really limited, ğŸ‘ ğŸ» welcome according to contribution guide (https://s2.antv.antgroup.com/manual/contribution) to submit PR. Get involved in open source projects together.

            If you have a problem, Or to [Issues] (https://github.com/antvis/S2/issues) and [Discussions] (https://github.com/antvis/S2/discussions) interested in a list of questions, Can directly claim and try to repair, help S2 better, look forward to in the [contributor list] (https://github.com/antvis/S2/graphs/contributors) saw your head.

      - name: Rejected
        if: github.event.label.name == 'âŒ won''t support'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç»è¿‡æˆ‘ä»¬çš„åå¤è®¨è®º, ä½ çš„éœ€æ±‚è¿‡äºå®šåˆ¶åŒ–ï¼Œä¸é€‚åˆç›´æ¥æ·»åŠ åˆ° S2 ä¸­, S2 ä½œä¸ºå¼€æºæ¡†æ¶ï¼Œåªä¼šè¿›è¡Œé€šç”¨èƒ½åŠ›çš„å¢å¼ºå’Œè‡ªå®šä¹‰æ¥å£çš„å¼€æ”¾ã€‚ä½ å¯ä»¥é€šè¿‡ S2 æä¾›çš„è‡ªå®šä¹‰èƒ½åŠ›è‡ªè¡Œå®ç°ï¼Œæ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}, After our repeated discussions, your needs are too customized and not suitable for implementing directly to S2. As an open source framework, S2 will only enhance general capabilities and open custom interfaces. You can implement it yourself through the customization capabilities provided by S2, thank you for your understanding.

      - name: Supported or fixed in 2.x
        if: github.event.label.name == 'âœ¨ supported or fixed in 2.x'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯¥åŠŸèƒ½æˆ–ç¼ºé™·å·²ç»åœ¨ `2.x` ç‰ˆæœ¬ä¸­æ”¯æŒæˆ–ä¿®å¤ï¼Œè¯·ä½¿ç”¨ `2.x` ç‰ˆæœ¬è¿›è¡Œå¼€å‘ï¼ˆ`1.x` ç‰ˆæœ¬ä¸å†ç»´æŠ¤ï¼‰, æ„Ÿè°¢ä½ çš„æ”¯æŒä¸ç†è§£ã€‚

            å¦‚æœ‰ä»»ä½• `2.x` ç‰ˆæœ¬é—®é¢˜ï¼Œæ¬¢è¿æ[issue](https://github.com/antvis/S2/issues) æˆ– [æŸ¥çœ‹æ–‡æ¡£](https://s2.antv.antgroup.com):

            ```bash
            yarn add @antv/s2
            yarn add @antv/s2-react
            yarn add @antv/s2-react-components
            yarn add @antv/s2-vue
            ```

            Hello, @${{ github.event.issue.user.login }}, This feature or defect has been supported or fixed in the '2.x' version, please use the '2.x' version for development (' 1.x 'version is no longer maintained), thank you for your support and understanding.

            Any `2.x` version issues, please go to [issue](https://github.com/antvis/S2/issues), or [view docs](https://s2.antv.antgroup.com), the first trial:

      - name: S2 Vue
        if: github.event.label.name == 's2-vue'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œ`@antv/s2-vue` ç°å·²åœæ­¢ç»´æŠ¤ï¼Œç”±äºç²¾åŠ›æŠ•å…¥æœ‰é™ï¼Œå‡ºäºç»´æŠ¤æˆæœ¬ï¼ŒåŒ…ä¸‹è½½é‡ç­‰å› ç´ ç»¼åˆè€ƒè™‘ï¼Œä» `2.0.0` æ­£å¼ç‰ˆåä¸å†ç»§ç»­æ›´æ–°ï¼Œè¯·åŸºäº `@antv/s2` è‡ªè¡Œå°è£…ï¼Œæˆ– fork ä»“åº“è¿›è¡ŒäºŒæ¬¡å¼€å‘ã€‚

            Hello, @${{ github.event.issue.user.login }}, `@antv/s2-vue` has stopped maintenance, due to limited energy investment, due to the comprehensive consideration of maintenance costs, package downloads and other factors, from the '2.0.0' official version will not continue to update, please based on '@antv/s2' self-encapsulation, or fork warehouse for secondary development.

      - name: G
        if: github.event.label.name == 'G'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¿™ä¸ªå±äºåº•å±‚æ¸²æŸ“å¼•æ“ [AntV/G](https://g.antv.antgroup.com/) çš„é—®é¢˜, éœ€è¦ç­‰å¾…åº•å±‚æ”¯æŒæˆ–ä¿®å¤å, ä¸Šå±‚æ‰èƒ½é€‚é…, è¯·è€å¿ƒç­‰å¾…, æ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}, This belongs to the underlying rendering engine AntV/G (https://g.antv.antgroup.com/), needs to wait for the underlying support or after repair, the upper can adapter, please wait patiently, thank you for your understanding.

