name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    if: github.actor != github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Need reproduce
        if: github.event.label.name == 'ğŸ¤” need reproduce'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æä¾›ä¸€ä¸ªå¯ä»¥åœ¨çº¿è®¿é—®çš„é“¾æ¥, æˆ–è€…ä½¿ç”¨ [codesandbox](https://codesandbox.io/s/29zle) æä¾›ç¤ºä¾‹å¹¶è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, please provide an accessible link or usage [codesandbox](https://codesandbox.io/s/29zle) to describe the reproduction steps. The issue will be closed without any replay within 15 days.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯ (å‚è€ƒ #852 #848), æä¾› gif, æˆªå›¾, ä»£ç ç‰‡æ®µ, é…ç½®ä¿¡æ¯, ç‰ˆæœ¬å·, å¯å¤ç°é“¾æ¥ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢! 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please complete the issue description (refer #852 #848), provide gifs, screenshots, config, version. And explain the reproduction steps in detail. Thanks so much for your cooperation! The issue will be closed without any replay within 15 days.

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯ (å‚è€ƒ #852 #848), æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€šã€‚

            Hello @${{ github.event.issue.user.login }}, please fill in the relevant information according to the issue template to facilitate communication efficiently (refer #852 #848). Thanks so much!

      - name: Enhancement
        if: github.event.label.name == 'âš¡ enhancement'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„å»ºè®®, æˆ‘ä»¬ä¼šåŠæ—¶è¯„ä¼°å’Œæ’æœŸ, è°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, thanks for your advice. We will evaluate and schedule in time. Thank you!

      - name: Bug
        if: github.event.label.name == 'ğŸ› bug'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå¾ˆæŠ±æ­‰ç»™ä½ å¸¦æ¥äº†ä¸å¥½çš„ä½“éªŒ, æˆ‘ä»¬ä¼šå°½å¿«æ’æŸ¥é—®é¢˜å¹¶ä¿®å¤, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, We are so sorry for the bad experience. We will troubleshoot and fix the problem as soon as possible. Please pay attention to the follow-up change logs.

      - name: Usage
        if: github.event.label.name == 'ğŸ™€ usage' || github.event.label.name == 'â”question'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}, Issue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚ä½ å¯ä»¥è¯•ç€åœ¨ [antv s2 discussions](https://github.com/antvis/S2/discussions) æ–°å¼€ä¸€ä¸ª discussion, é€‰æ‹© `ğŸ™Q&A` ç±»åˆ«è¿›è¡Œæé—®, æˆ‘ä»¬ä¼šåŠæ—¶è¿›è¡Œè§£ç­”, æ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}. The Issue section is used for bug feedback and requirement discussion. You could open a new discussion in [antv s2 discussions](https://github.com/antvis/S2/discussions), choose the `ğŸ™Q&A` category to ask questions. We will answer in time. Thanks so much for your understanding.

      - name: Accepted
        if: github.event.label.name == 'âœ… accepted'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç»è¿‡æˆ‘ä»¬çš„åå¤è®¨è®º, ä½ çš„éœ€æ±‚ç°å·²è¢«é‡‡çº³, æˆ‘ä»¬ä¼šæ’æœŸå¼€å‘, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—ã€‚

            Hello, @${{ github.event.issue.user.login }}, your feature request have been accepted after our repeated discussion. We will schedule the development, please pay attention to the follow-up release logs.

      - name: Rejected
        if: github.event.label.name == 'âŒ rejected'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç»è¿‡æˆ‘ä»¬çš„åå¤è®¨è®º, ä½ çš„éœ€æ±‚è¿‡äºå®šåˆ¶åŒ–ï¼Œä¸é€‚åˆç›´æ¥æ·»åŠ åˆ° S2 ä¸­, ä½ å¯ä»¥é€šè¿‡ S2 æä¾›çš„è‡ªå®šä¹‰èƒ½åŠ›è‡ªè¡Œå®ç°ï¼Œæ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}, your feature request is too customized to be directly implemented in S2 after our repeated discussion, you could implement it by yourself through the customization capabilities provided by S2. Thanks so much for your understanding.
