name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Need Reproduce
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æä¾›ä¸€ä¸ªå¯ä»¥åœ¨çº¿è®¿é—®çš„é“¾æ¥, æˆ–è€…ä½¿ç”¨[codesandbox](https://codesandbox.io/s/29zle) å¹¶è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, 7å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

            Hello, @${{ github.event.issue.user.login }}, please provide an accessible link or use[codesandbox](https://codesandbox.io/s/29zle) to describe the step. It will be closed if we receive no replay in 7 days.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·å®Œå–„ issue æè¿°, æä¾› gif, æˆªå›¾ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to trace the problem. Please complete the issue description, provide gifs, screenshots, etc. and explain the reproduction steps in detail. Thank you so much for being so cooperative!

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€šã€‚

            Hello @${{ github.event.issue.user.login }}, please fill in the relevant information according to the issue template, so that everyone can communicate efficiently. Thank you so much!

      - name: Enhancement
        if: github.event.label.name == 'âš¡ enhancement'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„å»ºè®®, æˆ‘ä»¬ä¼šåŠæ—¶è¯„ä¼°å’Œæ’æœŸ, è°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, thanks for your advice. We will evaluate and schedule in time. Thank you!

      - name: Bug
        if: github.event.label.name == 'ğŸ› bug'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå¾ˆæŠ±æ­‰ç»™ä½ å¸¦æ¥äº†ä¸å¥½çš„ä½“éªŒ, æˆ‘ä»¬ä¼šå°½å¿«æ’æŸ¥é—®é¢˜å¹¶ä¿®å¤, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, We are very sorry for the bad experience. We will troubleshoot and fix the problem as soon as possible. Please pay attention to the subsequent change logs.

      - name: Usage
        if: github.event.label.name == 'ğŸ™€ usage' || github.event.label.name == 'â”question'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒIssue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚ä½ å¯ä»¥è¯•ç€åœ¨ [antv s2 discussions](https://github.com/antvis/S2/discussions) æ–°å¼€ä¸€ä¸ª discussionï¼Œé€‰æ‹© `ğŸ™Q&A` ç±»åˆ«è¿›è¡Œæé—®, æˆ‘ä»¬ä¼šåŠæ—¶è¿›è¡Œè§£ç­”, æ„Ÿè°¢ä½ çš„ç†è§£ã€‚

            Hello, @${{ github.event.issue.user.login }}. The Issue section is used for bug feedback and requirement discussion. You can try to open a new discussion in [antv s2 discussions](https://github.com/antvis/S2/discussions), choose the `ğŸ™Q&A` category to ask questions, we will answer in time. Thank you so much for being so understanding.
