name: Issue Opend

on:
  issues:
    types: [opened]

jobs:
  issue-opend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue title
        if: github.event.issue.title == 'ğŸ¤”' || github.event.issue.title == 'ğŸ™' || github.event.issue.title == 'ğŸ›'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·ç¼–è¾‘ä½ çš„ issue æ ‡é¢˜, ä¸€ä¸ªè¨€ç®€æ„èµ…çš„ issue æ ‡é¢˜å¯ä»¥èŠ‚çœå¤§å®¶çš„æ—¶é—´, è¯·ä¸è¦å°†æ ‡é¢˜å½“åšæ­£æ–‡, æˆ–è€…ä¸ºç©ºã€‚

            Hello, @${{ github.event.issue.user.login }}, please edit your issue title. a concise issue title will save everyone time. please do not leave the title as the body or empty.

      # æ ‡é¢˜æˆ–æ­£æ–‡ (ç‰ˆæœ¬å·) å¸¦æœ‰ next, å¢åŠ æ ‡è®°ä¾¿äºç»Ÿè®¡
      - name: Auto Set Next Label
        if: contains(github.event.issue.title, 'next') || contains(github.event.issue.body, 'next')
        uses: actions-cool/issues-helper@main
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'next'

      - name: Auto Tips
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}:

            ### æ Issue é¡»çŸ¥

            âš ï¸ åœ¨æå‡ºé—®é¢˜å‰ï¼Œè¯·ç¡®ä¿ä½ å·²ç»ä»”ç»†é˜…è¯»ğŸ‘“/æœç´¢ğŸ”è¿‡ [å®˜æ–¹æ–‡æ¡£](https://s2.antv.antgroup.com) å’Œ [å¸¸è§é—®é¢˜](https://s2.antv.antgroup.com/manual/faq) ä»¥åŠ [å›¾è¡¨ç¤ºä¾‹](https://s2.antv.antgroup.com/examples), å¹¶ä¸”å·²ç»æœç´¢æŸ¥é˜…è¿‡ç›¸å…³ [Issues åˆ—è¡¨](https://github.com/antvis/S2/issues?q=is%3Aissue+is%3Aclosed) å’Œ [Discussions åˆ—è¡¨](https://github.com/antvis/S2/discussions). å½“ä½ ç¡®å®šè‡ªå·±çš„é—®é¢˜æ²¡æœ‰è§£å†³æ–¹æ¡ˆæ—¶ï¼Œè¯·æäº¤ issueã€‚ âš ï¸

            å¦‚æœæ˜¯ä½¿ç”¨é—®é¢˜ï¼Œä¸çŸ¥é“æ€ä¹ˆç”¨ï¼Œç§»æ­¥ [Discussions è®¨è®ºåŒº](https://github.com/antvis/S2/discussions) å¹¶æä¾› [æœ‰æ•ˆä¿¡æ¯](https://zhuanlan.zhihu.com/p/25795393) è¿›è¡Œ [æé—®](https://github.com/antvis/S2/discussions/new?category=q-a)ã€‚

            ### å‚ä¸ç¤¾åŒºå…±å»º

            **è¿™æ˜¯ä¸€ä¸ªå¼€æºé¡¹ç›®, æˆ‘ä»¬ä¹Ÿæœ‰ç¹å¿™çš„ä¸šåŠ¡è¦åš, æ˜¯ç”¨è‡ªå·±çš„ä¸šä½™æ—¶é—´åœ¨ç»´æŠ¤, ä¸ºçˆ±å‘ç”µ, ç²¾åŠ›æœ‰é™, æ‰€ä»¥æœ‰æ—¶å€™ issue å“åº”é€Ÿåº¦ä¸æ˜¯é‚£ä¹ˆåŠæ—¶, å¦‚æœä½ é‡åˆ°äº†é—®é¢˜, æˆ–è€…å¯¹ [Issues](https://github.com/antvis/S2/issues) å’Œ [Discussions](https://github.com/antvis/S2/discussions) åˆ—è¡¨çš„é—®é¢˜æ„Ÿå…´è¶£, å¯ä»¥ç›´æ¥è®¤é¢†å¹¶å°è¯•ä¿®å¤ ([è´¡çŒ®æŒ‡å—](https://s2.antv.antgroup.com/manual/contribution))ï¼Œå¸®åŠ© S2 å˜å¾—æ›´å¥½, è€Œä¸æ˜¯ä¸€å‘³çš„åŸ‹æ€¨å’Œå‚¬ä¿ƒ, æˆ‘ä»¬ä¸æ˜¯ç”²æ–¹ä¹™æ–¹çš„å…³ç³».**
