name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Need Reproduce
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æä¾›ä¸€ä¸ªå¯ä»¥åœ¨çº¿è®¿é—®çš„é“¾æ¥, æˆ–è€…ä½¿ç”¨[codesandbox](https://codesandbox.io/s/29zle) å¹¶è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, 7å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·å®Œå–„ issue æè¿°, æä¾› gif, æˆªå›¾ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢!

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€š,

      - name: Enhancement
        if: github.event.label.name == 'âš¡ enhancement'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„å»ºè®®, æˆ‘ä»¬ä¼šåŠæ—¶è¯„ä¼°å’Œæ’æœŸ, è°¢è°¢!

      - name: Usage
        if: github.event.label.name == 'ğŸ™€ usage' || github.event.label.name == 'â”question'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒIssue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚ä½ å¯ä»¥è¯•ç€åœ¨ [antv s2 discussions](https://github.com/antvis/S2/discussions) æ–°å¼€ä¸€ä¸ª discussionï¼Œé€‰æ‹© `ğŸ™Q&A` ç±»åˆ«è¿›è¡Œæé—®, æˆ‘ä»¬ä¼šåŠæ—¶è¿›è¡Œè§£ç­”, æ„Ÿè°¢ä½ çš„ç†è§£
