name: ğŸ¤– Sync to Gitee Mirror

on: [page_build, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ GitHub æºä»“åº“åœ°å€
          source-repo: git@github.com:antvis/S2.git
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç›®æ ‡ä»“åº“åœ°å€
          destination-repo: git@gitee.com:antv-s2/antv-s2.git

      - name: âœ… Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
          gitee-username:  afc163
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
          gitee-password:  ${{ secrets.GITEE_PASSWORD }}
          # å‚æ•°é»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œéœ€è¦æŒ‡å®š
          branch: gh-pages
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“
          gitee-repo: antv-s2/antv-s2

      - name: ğŸ”Š Sync to gitee success notify
        if: ${{ success() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "âœ… åŒæ­¥å›½å†…é•œåƒæˆåŠŸ",
                "text": "ğŸ”— ç‚¹å‡»è®¿é—®",
                "messageUrl": "https://antv-s2.gitee.io/zh",
                "picUrl": "https://gw.alipayobjects.com/zos/antfincdn/eg5FNSoci/5706bbeb-7b75-4f4f-8fa5-2ac02dc99c4a.png"
              }
            }

      - name: ğŸ”Š Sync to gitee failed notify
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "ğŸš¨ åŒæ­¥å›½å†…é•œåƒå¤±è´¥",
                "text": "ğŸ”— è¯·ç‚¹å‡»é“¾æ¥æŸ¥çœ‹å…·ä½“åŸå›  ğŸš‘",
                "messageUrl": "https://github.com/antvis/S2/actions/workflows/mirror.yml",
                "picUrl": "https://gw.alipayobjects.com/zos/antfincdn/eg5FNSoci/5706bbeb-7b75-4f4f-8fa5-2ac02dc99c4a.png"
              }
            }
