name: PR Labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Need test case or docs
        if: github.event.label.name == 'ğŸ™ need test cases or docs'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, ä¸ºäº†è®©ä»£ç æ›´å¥å£®, è¯·è¡¥å……ç›¸åº”å•å…ƒæµ‹è¯•, å¦‚æœæœ‰APIæ”¹åŠ¨, è¯·ä¿®æ”¹ [ç›¸åº”çš„æ–‡æ¡£](https://github.com/antvis/S2/tree/master/s2-site)

            Hello, @${{ github.event.pull_request.user.login }}, Thank you for your contribution. In order to make the code more robust, please supplement the corresponding unit tests, if there are API changes, please edit the [docs](https://github.com/antvis/S2/tree/master/s2-site).

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, è¯·æ ¹æ®æ¨¡æ¿å®Œå–„ PR æè¿°, è¯´æ˜å…¶æ”¹åŠ¨ç›®çš„å’Œç±»å‹, ä»¥ä¾¿äºæˆ‘ä»¬å¯ä»¥æ›´å¥½çš„è¿›è¡Œ Code Review

            Hello, @${{ github.event.pull_request.user.login }}, Thank you for your contribution. Please improve the PR description according to the template, and explain the purpose and type of change, so that we can conduct a better Code Review.
