name: PR Labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Need test case or docs
        if: github.event.label.name == 'ğŸ™ need test cases or docs'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, ä¸ºäº†è®©ä»£ç æ›´å¥å£®, è¯·è¡¥å……ç›¸åº”å•å…ƒæµ‹è¯•, å¦‚æœæœ‰ API æ”¹åŠ¨, è¯·ä¿®æ”¹ [ç›¸åº”çš„æ–‡æ¡£](https://github.com/antvis/S2/tree/master/s2-site)

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. In order to make the code more robust, please add the corresponding unit tests, and update the [docs](https://github.com/antvis/S2/tree/master/s2-site) if there are API changes.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, è¯·æ ¹æ®æ¨¡æ¿å®Œå–„ PR æè¿°, å¹¶ç«™åœ¨ç”¨æˆ·çš„è§’åº¦è¯´æ˜å…¶æ”¹åŠ¨ç›®çš„å’Œè§£å†³äº†ä»€ä¹ˆé—®é¢˜ (è€Œéä½ çš„è§£å†³æ–¹å¼), ä»¥ä¾¿äºæˆ‘ä»¬å¯ä»¥æ›´å¥½çš„è¿›è¡Œ Code Review, åŒæ—¶è¯·ç¡®ä¿å·²å…³è”ç›¸åº” issue (å¦‚æœ‰), æ£€æŸ¥ä½ çš„ commit æ˜¯å¦æœ‰æè¿°æ¸…æ¥šä½ è¿™ä¸ª PR æ‰€åšçš„äº‹æƒ…ã€‚

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. Please improve the PR description based on the template, and explain the purpose of the change and the problems solved from the perspective of users (not your solution), so that we can conduct a better Code Review. At the same time, please make sure corresponding issue is associated (if any) Meanwhile, please check whether your commit clearly describes what you do as a PR.
