name: ğŸ” Sync Site Lock

# è‡ªåŠ¨å‘å¸ƒ action æ‰§è¡Œå®Œæˆåå†æ‰§è¡Œ (æ— è®ºæˆåŠŸå¤±è´¥éƒ½ä¼šæ‰§è¡Œ)
on:
  workflow_run:
    workflows: ["ğŸš€ Auto Release"]
    types:
      - completed

jobs:
  sync-site-lock:
    runs-on: ubuntu-latest
    # è‡ªåŠ¨å‘å¸ƒæˆåŠŸå
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Sync Locale site @antv/s2 and @antv/s2-react lock
        run: yarn site:sync-s2-lock

      - name: Push lock
        run: |
          git checkout -b ci-sync-s2-lock
          git add .
          git commit -m "chore: ğŸ¤– auto sync site s2 lock"
          git push origin ci-sync-s2-lock -n

      # ä½¿ç”¨å®˜æ–¹çš„ github cli ä¾¿æ·çš„åˆ›å»º pr
      - name: Create PR
        run: |
          gh pr create -f --base master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
